package com.marketplace.shared.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.util.List;
import java.util.UUID;

/**
 * Request to create a new user (from Auth Service to User Service).
 * Version: 1.0.0
 */
@Schema(description = "Request to create a new user")
public record CreateUserRequest(
    @NotNull(message = "User ID is required")
    @Schema(description = "User ID (generated by Auth Service)", example = "123e4567-e89b-12d3-a456-426614174000", requiredMode = Schema.RequiredMode.REQUIRED)
    UUID userId,
    
    @NotBlank(message = "Email is required")
    @Email(message = "Email must be valid")
    @Schema(description = "Email address", example = "user@example.com", requiredMode = Schema.RequiredMode.REQUIRED)
    String email,
    
    @NotBlank(message = "Name is required")
    @Size(min = 2, max = 100, message = "Name must be between 2 and 100 characters")
    @Schema(description = "Full name", example = "John Doe", requiredMode = Schema.RequiredMode.REQUIRED)
    String name,
    
    @NotNull(message = "Roles are required")
    @Size(min = 1, message = "At least one role is required")
    @Schema(description = "User roles", example = "[\"CUSTOMER\"]", requiredMode = Schema.RequiredMode.REQUIRED)
    List<String> roles
) {
}
