pipeline:
  name: auth_service_Build_Deploy
  identifier: auth_service_build_deploy
  projectIdentifier: javatodoapp  # UPDATE: Use your Harness project identifier
  orgIdentifier: default
  tags:
    service: auth-service
    type: microservice
  
  # Pipeline-level variables - Configured for auth-service
  variables:
    - name: serviceName
      type: String
      description: "Service directory name"
      required: true
      value: auth-service
    
    - name: artifactId
      type: String
      description: "Maven artifactId from pom.xml"
      required: true
      value: auth-service
    
    - name: jfrogBaseUrl
      type: String
      description: "JFrog Artifactory base URL (without repo name)"
      required: true
      value: https://yourcompany.jfrog.io/artifactory  # UPDATE: Your JFrog instance URL
    
    - name: jfrogRepoName
      type: String
      description: "JFrog repository name for snapshots"
      required: true
      value: libs-snapshot-local
    
    - name: dynamicVersion
      type: String
      description: "Dynamic version with build number"
      required: true
      value: 1.0.0-<+pipeline.sequenceId>
  
  properties:
    ci:
      codebase:
        connectorRef: githubmendelev  # UPDATE: Use your GitHub connector if different
        build: <+input>
  
  stages:
    - stage:
        name: Build_and_Deploy
        identifier: Build_and_Deploy
        description: Build auth-service and deploy to JFrog Artifactory
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              # ============================================================
              # STEP 1: Generate Maven Settings with JFrog Credentials
              # ============================================================
              - step:
                  type: Run
                  name: Generate_Maven_Settings
                  identifier: Generate_Maven_Settings
                  spec:
                    image: maven:3.9-eclipse-temurin-21
                    shell: Sh
                    command: |
                      mkdir -p ~/.m2
                      
                      # Generate settings.xml with JFrog credentials and deployment repository
                      cat > ~/.m2/settings.xml << 'EOF'
                      <?xml version="1.0" encoding="UTF-8"?>
                      <settings xmlns="http://maven.apache.org/SETTINGS/1.2.0"
                                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">
                        
                        <!-- Authentication for JFrog Artifactory -->
                        <servers>
                          <server>
                            <id>snapshots</id>
                            <username><+secrets.getValue("jfrog_username")></username>
                            <password><+secrets.getValue("jfrog_token")></password>
                          </server>
                        </servers>
                        
                        <!-- Active profile for deployment configuration -->
                        <profiles>
                          <profile>
                            <id>artifactory-deploy</id>
                            <activation>
                              <activeByDefault>true</activeByDefault>
                            </activation>
                            <properties>
                              <altDeploymentRepository>snapshots::default::<+pipeline.variables.jfrogBaseUrl>/<+pipeline.variables.jfrogRepoName></altDeploymentRepository>
                            </properties>
                          </profile>
                        </profiles>
                      </settings>
                      EOF
                      
                      echo "Maven settings.xml generated successfully"
                      echo "=========================================="
                      echo "Service: auth-service"
                      echo "Target repository: <+pipeline.variables.jfrogBaseUrl>/<+pipeline.variables.jfrogRepoName>"
                      echo "Version: <+pipeline.variables.dynamicVersion>"
                      echo "=========================================="
              
              # ============================================================
              # STEP 2: Run Unit Tests
              # ============================================================
              - step:
                  type: Run
                  name: Unit_Tests
                  identifier: Unit_Tests
                  spec:
                    image: maven:3.9-eclipse-temurin-21
                    shell: Sh
                    command: |
                      echo "Running tests for auth-service..."
                      cd <+pipeline.variables.serviceName> && mvn -B test -Drevision=<+pipeline.variables.dynamicVersion>
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/target/surefire-reports/*.xml"
              
              # ============================================================
              # STEP 3: Deploy to JFrog Artifactory
              # ============================================================
              - step:
                  type: Run
                  name: Deploy_to_Artifactory
                  identifier: Deploy_to_Artifactory
                  spec:
                    image: maven:3.9-eclipse-temurin-21
                    shell: Sh
                    command: |
                      # Regenerate Maven settings.xml with JFrog credentials
                      mkdir -p ~/.m2
                      cat > ~/.m2/settings.xml << 'EOF'
                      <?xml version="1.0" encoding="UTF-8"?>
                      <settings xmlns="http://maven.apache.org/SETTINGS/1.2.0"
                                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">
                        <servers>
                          <server>
                            <id>snapshots</id>
                            <username><+secrets.getValue("jfrog_username")></username>
                            <password><+secrets.getValue("jfrog_token")></password>
                          </server>
                        </servers>
                        <profiles>
                          <profile>
                            <id>artifactory-deploy</id>
                            <activation>
                              <activeByDefault>true</activeByDefault>
                            </activation>
                            <properties>
                              <altDeploymentRepository>snapshots::default::<+pipeline.variables.jfrogBaseUrl>/<+pipeline.variables.jfrogRepoName></altDeploymentRepository>
                            </properties>
                          </profile>
                        </profiles>
                      </settings>
                      EOF
                      
                      echo "Maven settings.xml configured"
                      echo "=========================================="
                      echo "Deploying auth-service"
                      echo "Service: <+pipeline.variables.serviceName>"
                      echo "Artifact ID: <+pipeline.variables.artifactId>"
                      echo "Version: <+pipeline.variables.dynamicVersion>"
                      echo "Repository: <+pipeline.variables.jfrogBaseUrl>/<+pipeline.variables.jfrogRepoName>"
                      echo "=========================================="
                      
                      # Deploy artifact to JFrog Artifactory
                      cd <+pipeline.variables.serviceName> && \
                        mvn -B deploy \
                          -Drevision=<+pipeline.variables.dynamicVersion> \
                          -DaltDeploymentRepository=snapshots::default::<+pipeline.variables.jfrogBaseUrl>/<+pipeline.variables.jfrogRepoName> \
                          -DskipTests
                      
                      echo ""
                      echo "=========================================="
                      echo "✅ Deployment completed successfully!"
                      echo "=========================================="
                      echo "Artifact: com.marketplace:auth-service:<+pipeline.variables.dynamicVersion>"
                      echo "Repository: <+pipeline.variables.jfrogRepoName>"
                      echo ""
                      echo "Verify in JFrog Artifactory:"
                      echo "<+pipeline.variables.jfrogBaseUrl>/<+pipeline.variables.jfrogRepoName>/com/marketplace/auth-service/<+pipeline.variables.dynamicVersion>/"
