pipeline:
  name: auth_service_Build_Deploy
  identifier: auth_service_build_deploy
  projectIdentifier: digitalmarketplace
  orgIdentifier: default
  tags:
    service: auth-service
    type: microservice
  variables:
    - name: serviceName
      type: String
      description: Service directory name
      required: true
      value: auth-service
    - name: artifactId
      type: String
      description: Maven artifactId from pom.xml
      required: true
      value: auth-service
    - name: jfrogBaseUrl
      type: String
      description: JFrog Artifactory base URL (without repo name)
      required: true
      value: https://yourcompany.jfrog.io/artifactory
    - name: jfrogRepoName
      type: String
      description: JFrog repository name for snapshots
      required: true
      value: libs-snapshot-local
    - name: dynamicVersion
      type: String
      description: Dynamic version with build number
      required: true
      value: 1.0.0-<+pipeline.sequenceId>
  properties:
    ci:
      codebase:
        connectorRef: githubmendelev
        build: <+input>
  stages:
    - stage:
        name: Build_and_Deploy
        identifier: Build_and_Deploy
        description: Build auth-service and deploy to JFrog Artifactory
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: Generate_Maven_Settings
                  identifier: Generate_Maven_Settings
                  template:
                    templateRef: org.Generate_Maven_Settings
                    versionLabel: version1
                    gitBranch: main
              - step:
                  name: Deploy_to_Artifactory
                  identifier: Deploy_to_Artifactory
                  template:
                    templateRef: org.Deploy_to_Artifactory
                    versionLabel: version1
                    gitBranch: main
