pipeline:
  name: order_service_build
  identifier: order_service_build
  projectIdentifier: digitalmarketplace
  orgIdentifier: default
  tags: {}
  variables:
    - name: serviceName
      type: String
      description: Service directory name
      required: true
      value: order-service
    - name: artifactId
      type: String
      description: Maven artifactId from pom.xml
      required: true
      value: order-service
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1766587643054
        repoName: Mendelev/Digital-Marketplace
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build_Service
                  identifier: Build_Service
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.9-eclipse-temurin-21
                    shell: Sh
                    command: |
                      echo "Installing shared-dtos..."
                      cd common/shared-dtos && mvn clean install -DskipTests
                      echo "Shared dependencies installed successfully"
                      echo ""
                      
                      echo "Building <+pipeline.variables.serviceName>..."
                      cd ../../<+pipeline.variables.serviceName> && \
                        mvn -B clean package -DskipTests
                      
                      echo "Build completed successfully"
                      ls -lh target/*.jar
