pipeline:
  name: payment_service_build
  identifier: payment_service_build
  projectIdentifier: digitalmarketplace
  orgIdentifier: default
  tags: {}
  variables:
    - name: serviceName
      type: String
      description: "Service directory name"
      required: true
      value: payment-service
    - name: artifactId
      type: String
      description: "Maven artifactId from pom.xml"
      required: true
      value: payment-service
    - name: jfrogBaseUrl
      type: String
      description: "JFrog Artifactory base URL (without repo name)"
      required: true
      value: https://trialq6tyqg.jfrog.io/artifactory
    - name: jfrogRepoName
      type: String
      description: "JFrog repository name for snapshots"
      required: true
      value: libs-snapshot-local
    - name: dynamicVersion
      type: String
      description: "Dynamic version with build number"
      required: false
      value: ""
      default: ""
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1766587643054
        repoName: Mendelev/Digital-Marketplace
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  name: Generate_Maven_Settings
                  identifier: Generate_Maven_Settings
                  template:
                    templateRef: org.Generate_Maven_Settings
                    versionLabel: version1
              - step:
                  name: Deploy_to_Artifactory
                  identifier: Deploy_to_Artifactory
                  template:
                    templateRef: org.Deploy_to_Artifactory
                    versionLabel: version1
